# Uncomment the next line to define a global platform for your project

target 'Schoodle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Toast-Swift'
  pod 'SwiftyJSON'
  pod 'SideMenu', '~> 6.0'
end
